### ISSUE TITLE
Blender 2.73

### ISSUE THREAD

**Issue by NNois** [maybites/blender.script.io_export_svg#2]
Hi,
The exporter doesn't shows up a least on blender 2.73, is it supposed to be compatible ?

**Comment by maybites** [comment]
It works with 2.73, at least on OSX 10.9. There might be an issue with Windows but I cannot confirm it.

**Comment by yodus** [comment]
Try to install it manually. It worked for me in blender 2.76 (Win10)
- Just copy _io_export_svg_ to _c:\Users<user name>\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\_. 
- Enabled it in user preferences
