### ISSUE TITLE
SVG-Export 

### ISSUE THREAD

**Issue by gl2748** [maybites/blender.script.io_export_svg#4]
Hey in your docs you comment:

> "This script was only created to accomodate the missing export functionality by the built-in Importer SVG script. Once the exporting funcionality of the built in script is released, development of this script will stop."

Did this happen? I can't find a Blender  SVG exporter for curves apart from yours... if it's natively supported by Blender where can I find it? Don't want to use  the 'Freestyle Render' SVG export ...

Thanks.

**Comment by maybites** [comment]
I read once somewhere about plans to implement it, but to my knowledge this exporter is the only one.

**Comment by gl2748** [comment]
Thanks. If I was to do some work contributing to it. What features would you implement first? e.g. Exporting more than 1 curve at a time? Or similar. 

Thanks

**Comment by maybites** [comment]
1. Selecting more than one and exporting all of them into one file would be excellent.

2. Also nice would be to select more than one and saving each into its own file named after each objects name.

But 1. seems to be the most useful addition.
